import CaseStudy from './CaseStudy';
import { DataTable, Shot } from './ArticleLayout';

export default function ArabicNumerals() {
  return <CaseStudy slug="arabic-numeral-ocr-speech" designTitle="Prototype Design"
    dataVisual={<Shot src="/img/arabic-interface.webp" alt="Static view of the original Arabic numeral prototype with manual input and historical image controls" w={1170} h={431} caption="Static capture of the original public interface. The pictured image controls belong to the unavailable historical extraction path; this portfolio does not enable upload." />}
    designVisual={<Shot src="/img/arabic-speech-flow.webp" alt="Manual numeral input passes through range validation, number decomposition and local audio playback" w={1200} h={675} caption="Explanatory schematic of the documented manual path: validate 0–1,000,000, decompose the number, then order local audio segments." />}
    summary={['This Arabic-interface prototype converts manually entered numbers from 0 to 1,000,000 into spoken output assembled from local audio segments. It also contains an experimental image-extraction path that parses Arabic-Indic and Western digits returned by an external service.', 'The public repository confirms that the external extraction service is no longer available. Manual number-to-speech composition remains the documented working path. No recognition benchmark is claimed, and the portfolio does not expose image upload or an unverified demo.']}
    data={['The speech output is assembled from local recordings of units, tens, hundreds, scale words, and connectors. This avoids recording every number within the supported range.', 'The historical image flow resized a selected or camera-captured image in the browser and uploaded it to an external backend. Its digit response was parsed before speech composition; the service is now unavailable.']}
    approach={['Validate the manually entered number against the supported range.', 'Break the number into components used by Arabic spoken-number construction.', 'Select and order local audio segments and connectors.', 'Play the composed sequence in the Arabic RTL interface.', 'Keep the unavailable image-extraction path distinct from the documented manual-input functionality.']}
    design="The manual path is input validation → number decomposition → ordered audio segments → playback. The image path historically inserted a third-party extraction request before numeral parsing. Speech composition and image recognition are separate components with separate failure modes."
    evaluation={<DataTable caption="Documented prototype functionality" headers={['Path', 'Status']} rows={[
      ['Manual number to composed Arabic speech', 'Documented for 0–1,000,000'], ['Image upload or camera extraction', 'Unavailable external service'], ['Arabic-Indic and Western digit parsing', 'Implemented for extraction responses'], ['Recognition accuracy', 'No benchmark documented'],
    ]} />}
    findings={['A finite collection of recordings can compose many spoken numbers.', 'The manual path does not depend on the unavailable extraction service.', 'An upload interface can appear complete while its external dependency prevents the feature from working.']}
    recommendation="Review the source as a numeral-parsing and audio-composition prototype. Any restored image flow needs a maintained backend, explicit disclosure that images leave the browser, defined retention handling, error states, and an independently evaluated recognition model."
    limitations={['This is a prototype, not a reliable OCR or general text-to-speech service.', 'The external image-extraction endpoint is unavailable and has no local fallback.', 'Uploaded images historically left the browser; the old interface did not disclose that behavior.', 'Recognition accuracy was not measured; pronunciation quality depends on the recorded audio segments.', 'Values outside 0–1,000,000 are rejected rather than approximated.']}
    stack={['JavaScript', 'HTML', 'CSS', 'Browser Audio', 'Arabic RTL', 'External OCR API (unavailable)']}
    contribution="I implemented the Arabic interface, numeral handling, audio composition, and external-service integration as an independent prototype. The takeaway is to distinguish a locally reproducible feature from a dependency-backed experiment, and to explain that boundary clearly to users."
  />;
}
