import { Link } from 'react-router';
import CaseStudy from './CaseStudy';
import { DataTable, Shot } from './ArticleLayout';
import s from './PsDiscSentiment.module.css';

function Marks() {
  return <span className={s.marks} aria-hidden="true"><span className={s.mT}>△</span><span className={s.mC}>◯</span><span className={s.mX}>✕</span><span className={s.mS}>◻</span></span>;
}
export default function PsDiscSentiment() {
  return <CaseStudy slug="playstation-disc-sentiment"
    summary={['This independent project explores 56,677 collected public reactions to a PlayStation-related post about physical discs. Multilingual transformer-based sentiment classification assigns negative, neutral, and positive labels, then an interactive dashboard lets readers explore the conversation by language and day.', 'Negative labels account for 63.0% of the shipped dataset, compared with 10.2% positive and 26.8% neutral. These findings describe the collected conversation, not a representative survey of PlayStation customers or independent verification of a product-policy announcement.']}
    data={['The supplied dashboard export contains 56,677 labeled reactions and day labels for Jul 1 and Jul 2. The original workflow describes collecting replies, quotes, and broader mentions, followed by deduplication and removal of empty content.', 'The public aggregate export does not preserve the complete acquisition query, collection log, or per-class model probabilities. Day labels describe the supplied export; they do not establish exhaustive coverage of the conversation.']}
    dataVisual={<Shot src="/img/ps-tweet.webp" alt="PlayStation-related source post supplied with the sentiment project" w={840} h={621} caption="The supplied source post provides the collection context. The study analyzes responses to the post rather than independently verifying its policy claim." />}
    approach={['Collect public reactions associated with the source post.', 'Prepare reaction text and metadata, using identifier-based deduplication in the original workflow.', 'Apply multilingual transformer-based sentiment classification.', 'Aggregate labeled reactions by day, language, and sentiment.', 'Present filters, distributions, and selected examples with explicit sampling limits.']}
    design="A compact day/language/sentiment contingency table drives the interactive dashboard. Cross-filtering lets each chart show its own distribution within the other active filters. Net sentiment is the share of positive labels minus the share of negative labels; it is not an average of model confidence scores."
    evaluation={<><p>The dashboard totals reconcile to the 56,677-record export. No independently annotated evaluation set is provided, so a classification-accuracy score is not claimed.</p><DataTable caption="Sentiment labels in the complete supplied export" headers={['Label', 'Reactions', 'Share']} rows={[
      ['Negative', '35,707', '63.0%'], ['Neutral', '15,190', '26.8%'], ['Positive', '5,780', '10.2%'],
    ]} /><p>The resulting net sentiment is approximately −0.53. The earlier probability-based average of −0.44 cannot be reconstructed from this label-only export and is not used as a dashboard statistic.</p></>}
    evaluationVisual={<div className={s.cta}><div className={s.ctaInfo}><Marks /><div><p className={s.ctaTitle}>Interactive Sentiment Dashboard</p><div className={s.mini} aria-hidden="true"><span className={s.miniNeg} style={{ width: '63%' }} /><span className={s.miniNeu} style={{ width: '26.8%' }} /><span className={s.miniPos} style={{ width: '10.2%' }} /></div><p className={s.miniLbl}>56,677 reactions · sentiment, language, and day filters</p></div></div><Link className={s.launch} to="/projects/playstation-disc-sentiment/dashboard">Explore dashboard</Link></div>}
    findings={['Negative labels substantially outnumber positive labels in this collected conversation.', 'English represents the largest labeled language group; language coverage is uneven.', 'The two supplied day groups contain different volumes, so proportions and absolute counts answer different questions.', 'Filtering improves exploration but cannot remove collection bias or establish customer-wide sentiment.']}
    recommendation="Use the dashboard to explore themes and identify questions for qualitative review. Combine social listening with representative research before making customer or product decisions."
    limitations={['Public reactions are not a representative sample of all PlayStation customers.', 'Bots, repeated content, sarcasm, ambiguous language, and classification errors may affect the result.', 'Language coverage and platform-selection bias limit generalization.', 'The aggregate export does not allow independent auditing of the collection query, deduplication, or model-probability calculations.']}
    stack={['Python', 'CardiffNLP twitter-XLM-RoBERTa', 'Transformers', 'pandas', 'React', 'TypeScript']}
    contribution="I developed the collection and sentiment-analysis workflow and connected the results to an interactive reporting experience. The central lesson was that a useful dashboard should make its units, filters, and limitations as easy to understand as its headline result."
  />;
}
